export const ACTION_GET_USER_DETAILS = 'ACTION_GET_USER_DETAILS';
export const ACTION_SAVE_USER_DETAILS = 'ACTION_SAVE_USER_DETAILS';
export const ACTION_GET_MASTER_DATA = 'ACTION_GET_MASTER_DATA';
export const ACTION_GET_MASTER_DATA_STORE = 'ACTION_GET_MASTER_DATA_STORE';
