export const ACTION_GOOGLE_LOGIN_REQUEST = 'ACTION_GOOGLE_LOGIN_REQUEST';
export const ACTION_STORE_USER_PROFILE_INFO = 'ACTION_STORE_USER_PROFILE_INFO';

export const ACTION_LOGOUT = 'ACTION_LOGOUT';
export const ACTION_LOGIN_CLEAR = 'ACTION_LOGIN_CLEAR';
